// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "new_serverip": string;
      "sourceLang": string;
      "targetLang": string;
      "sourceLangSelect": string;
      "targetLangSelect": string;
      "service": string;
      "serviceSelect": string;
      "outputMono": boolean;
      "outputDual": boolean;
      "skipLastPages": number;
      "qps": number;
      "poolSize": number;
      "rename": boolean;
      "openAfterTranslate": boolean;
      "notifyOnTranslationComplete": boolean;
      "fontFamily": string;
      "ocr": boolean;
      "autoOcr": boolean;
      "translateTableText": boolean;
      "skipReferences": boolean;
      "skipTextChecks": boolean;
      "noWatermark": boolean;
      "disableTermExtraction": boolean;
      "dialog-service": string;
      "dialog-serviceSelect": string;
    };
  }
}
