// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "new_serverip": string;
      "sourceLang": string;
      "targetLang": string;
      "sourceLangSelect": string;
      "targetLangSelect": string;
      "service": string;
      "serviceSelect": string;
      "outputMono": boolean;
      "outputDual": boolean;
      "skipLastPages": number;
      "qps": number;
      "poolSize": number;
      "rename": boolean;
      "attachmentTitleTemplate": string;
      "openAfterTranslate": boolean;
      "notifyOnTranslationComplete": boolean;
      "fontFamily": string;
      "ocr": boolean;
      "autoOcr": boolean;
      "translateTableText": boolean;
      "skipReferences": boolean;
      "skipTextChecks": boolean;
      "noWatermark": boolean;
      "disableTermExtraction": boolean;
      "glossaryEntries": string;
      "glossaryPackSelections": string;
      "semanticReview": boolean;
      "reviewPreferenceMigrationVersion": number;
      "dialog-service": string;
      "dialog-serviceSelect": string;
      "selectedApiKey": string;
      "profileSchemaVersion": number;
      "selectionTranslationProvider": string;
      "selectionApiKey": string;
      "selectionDictionary": string;
      "selectionDictionaryFallback": string;
      "selectionTrigger": string;
      "selectionStream": boolean;
      "selectionPreferenceVersion": number;
      "selectionAutoDictionary": boolean;
      "attachmentTitleLayout": string;
      "selectionDisplayMode": string;
      "selectionPopupWidth": number;
      "selectionPopupHeight": number;
      "selectionPopupPinned": boolean;
      "selectionPopupLeft": number;
      "selectionPopupTop": number;
    };
  }
}
